name: kolaylokma
description: "Kolaylokma"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  permission_handler: ^11.3.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.5.0
  uuid: ^4.3.3
  image_picker: ^1.0.7
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - web/icons/logo.png
    - web/icons/register.png
    - web/icons/login.png
    - web/icons/forgot-password.png
    - web/icons/verification.png
    - web/icons/reset-password.png
  uses-material-design: true
